### ISSUE TITLE
utils

### ISSUE THREAD

**Issue by zf718** [JNAIC/DPMs-for-Audio-Data-Augmentation#1]
Can you open source the file utils.py？

**Comment by dongdongunique** [comment]
of course, sorry for the delay

**Comment by dongdongunique** [comment]
sorry for the missing file and the inconvenience brought by it

**Comment by zf718** [comment]
Thank you very much!

**Comment by dongdongunique** [comment]
https://huggingface.co/docs/diffusers/en/index  The diffusers I used in this code is outdated, you may refer to the up-to-date one.

**Comment by zf718** [comment]
ok , I will refer it.

**Comment by dongdongunique** [comment]
if you have any other problems, you can open new issues. I will close this one, is this ok?

**Comment by dongdongunique** [comment]
sorry again for the delay and inconvenience
